### ISSUE TITLE
Suggestion for Xmlns

### ISSUE THREAD

**Issue by ReedCopsey** [JohanLarsson/Gu.Wpf.GridExtensions#2]
Instead of: 
```
[assembly: XmlnsDefinition("https://github.com/JohanLarsson/Gu.Wpf.GridExtensions", "Gu.Wpf.GridExtensions")]
[assembly: XmlnsPrefix("https://github.com/JohanLarsson/Gu.Wpf.GridExtensions", "grid")]
```

I'd recommend standardizing on a single URL for all "gu" projects, so you can use multiple without redefining your xaml, such as:

```
[assembly: XmlnsDefinition("https://github.com/JohanLarsson/Gu.Wpf", "Gu.Wpf.GridExtensions")]
[assembly: XmlnsPrefix("https://github.com/JohanLarsson/Gu.Wpf", "gu")]
```

**Comment by ReedCopsey** [comment]
That commit shouldn't close this issue.  Please reopen.

**Comment by ReedCopsey** [comment]
This doesn't quite do what I was suggesting... If you want to make this work with `gu` "globally", you'd have to use a single, unified URL.

**Comment by JohanLarsson** [comment]
Thanks!
